theme = "hex-toxic-transparent"

[editor]
line-number = "relative"
bufferline = "always"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-l = ":buffer-next"
C-h = ":buffer-previous"
C-w = ":bc"
y = { y = ["extend_line_below", "yank"] }

[keys.normal.n]
n = "goto_next_change"
p = "goto_prev_change"

[editor.cursor-shape]
insert = "bar"
